### ISSUE TITLE
Mapzen is going away 😑

### ISSUE THREAD

**Issue by achavez** [DallasMorningNews/jquery-mapzen-autocomplete#2]
We need to find a replacement and either rewrite this or roll a new plug-in.

Mapzen suggested some replacements in their [migration guide](https://mapzen.com/blog/migration/):

> For search and geocoding, you may want to consider these services:
> - [Nominatim](http://nominatim.openstreetmap.org/)
> - [OpenCage Data](https://geocoder.opencagedata.com/)
> - [OSMNames](https://osmnames.org/)
> - [Mapbox Search API](https://www.mapbox.com/geocoding/)
>
> Mapzen Search was backed by [Pelias](https://github.com/pelias/), an open source project. Read below for how to run this service locally.

It looks like the price on the replacements varies quite a lot so that may end up being the deciding factor.

**Comment by achavez** [comment]
I looked into the four options recommended by Mapzen and tried a search for "1954 Commerce St, Dallas, TX" on each:

| Service | Price | Test results
| -- | -- | --
| Nominatim | hosted options available, free version [doesn't support autocomplete](https://operations.osmfoundation.org/policies/nominatim/) | [Failed](http://nominatim.openstreetmap.org/search.php?q=1954+Commerce+St%2C+Dallas%2C+TX&polygon_geojson=1&viewbox=) (place data only)
| OpenCage Data | free for 2,500/day and 1/sec.; $50 for 10,000/day and 10/sec.  | [Worked](https://geocoder.opencagedata.com/demo)
| OSMNames API | free with $40/mo. [tile hosting plan](https://www.tilehosting.com/#plans) | [Failed](https://osmnames.org/#q=1954%20Commerce%20St%2C%20Dallas%2C%20TX) (place data only)
| Mapbox Search API | $0.50 per 1,000 tile requests, but results must be displayed on a Mapbox map, which requires a $499/mo. subscription (because paywall) | Worked

I also think we should rule out running our instance of Pelias given the substantial complexity and upkeep. Per [their installation docs](http://pelias.io/install.html), we need an ElasticSearch instance and an API server. Even using existing, shared resources I think we can expect the cost to approach that of the less expensive services above.

Given all of that, and because we know that Google is cost prohibitive because of the paywall, I'd suggest OpenCage Data out of Mapzen's recommended replacements.

**Comment by achavez** [comment]
I think the concurrency is the main issue - specifically the 1 per second. With the autocomplete lookup we end up sending 1 per second, so my fear is that when we start promoting this we'll exceed that during peak times.

I do think we'll use this for other projects where we need an address lookup, FWIW.

**Comment by achavez** [comment]
I'll wire this up with OpenCage Data. I did also investigate SmartyStreets, which is another popular vendor. However, it seems they only do address verification and don't do forward geocoding with the verified addresses.

**Comment by achavez** [comment]
OK, tapping the breaks real quick. Here's a potentially better option: https://community.algolia.com/places/

It's free up to 100,000 queries/mo. and the autocomplete widget is already built and looks really slick: https://community.algolia.com/places/

I've looked at the code on Github and the docs and it looks like it can be used as a replacement not just for Mapzen, but for this entirely library, which I'm definitely in favor of. And I think the user experience will be much better. Check out, for example: https://community.algolia.com/places/

@jdhancock88, if you're cool with this I can swap out what's in voter guide and then deprecate (for now) this library. I think we can keep the code around just in case we someday have to replace Algolia again.

**Comment by jdhancock88** [comment]
Go for it, @achavez

**Comment by achavez** [comment]
Closing in favor of switching to Algolia

**Comment by achavez** [comment]
Re-opening this because Algolia turned out to be stupid expensive ...
